apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule

metadata:
  name: team-a-rules
  namespace: monitoring

spec:
  groups:

    - name: team-a-alerts

      rules:

        - alert: TeamATargetDown

          expr: up{team="team-a"} == 0

          for: 1m

          labels:
            severity: critical

          annotations:
            summary: Team A target is down