name: Validate

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install yamllint
        run: pip install yamllint

      - name: YAML Lint
        run: yamllint .

      - name: Download vmalert 
        run: wget https://github.com/VictoriaMetrics/VictoriaMetrics/releases/latest/download/vmalert-linux-amd64 chmod +x vmalert-linux-amd64 
        
      - name: Validate all rule files 
        run: |
            find teams -name "vmrule.yaml" -exec \ 
            ./vmalert-linux-amd64 -rule {} -dryRun \;