name: Validate

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install yamllint
        run: pip install yamllint

      - name: YAML Lint
        run: yamllint .

      - name: Download VictoriaMetrics
        run: |
          wget https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v1.143.0/victoria-metrics-linux-amd64-v1.143.0.tar.gz 
          tar -xzf victoria-metrics-linux-amd64-v1.143.0.tar.gz

      - name: Validate all rule files
        run: |
            find teams -name "vmrule.yaml" -exec \
            ./vmalert-linux-amd64 -rule {} -dryRun \;